### ISSUE TITLE
Maybe update the dependencies?

### ISSUE THREAD

**Issue by Kosrotoff** [SMAY666/fullstack-app-monorepo#8]
![image](https://user-images.githubusercontent.com/50526865/183714307-d53b5a48-bb20-4fcd-aeb1-790d7dde9016.png)

![image](https://user-images.githubusercontent.com/50526865/183714261-a39c828e-3f92-4ec0-a5ca-75ff9fb9cd45.png)

**Comment by sm4yy** [comment]
Updated
